// GENERATED by scripts/gen-agent-faces.mjs. Do not edit by hand.
//
// The eleven portrait/banner pairs in `public/agent-faces/`, in source order, as a typed list. The
// list is built at BUILD TIME rather than read from a directory at runtime for the reason
// `agentArtFiles.ts` gives one asset set over: a browser cannot list a directory, and a server that
// could would be answering a question whose answer must be identical on every replica.
//
// THE ORDER IS THE MAPPING. An agent takes the entry at its own position in its workspace's
// creation order, so a list in a different order hands every agent in the workspace a different
// face. The ids are zero-padded precisely so that "source order" and "sorted order" are the same
// sequence on every platform — directory iteration order is not stable across them, and this
// project has already been bitten once by a platform-dependent path.
//
// `test:agent-faces` asserts this matches what is actually in `public/agent-faces`.

export interface AgentFaceFiles {
  /** The value `agents.picture` stores. */
  readonly id: string;
  /** The square portrait, drawn on the character's own hue and full bleed to its edges. */
  readonly portrait: string;
  /** The banner band, 2:1, in the same hue as the portrait it belongs to. */
  readonly banner: string;
}

export const AGENT_FACE_FILES: readonly AgentFaceFiles[] = [
  { id: "avatar-01", portrait: "avatar-01.png", banner: "avatar-01-bg.jpg" },
  { id: "avatar-02", portrait: "avatar-02.png", banner: "avatar-02-bg.jpg" },
  { id: "avatar-03", portrait: "avatar-03.png", banner: "avatar-03-bg.jpg" },
  { id: "avatar-04", portrait: "avatar-04.png", banner: "avatar-04-bg.jpg" },
  { id: "avatar-05", portrait: "avatar-05.png", banner: "avatar-05-bg.jpg" },
  { id: "avatar-06", portrait: "avatar-06.png", banner: "avatar-06-bg.jpg" },
  { id: "avatar-07", portrait: "avatar-07.png", banner: "avatar-07-bg.jpg" },
  { id: "avatar-08", portrait: "avatar-08.png", banner: "avatar-08-bg.jpg" },
  { id: "avatar-09", portrait: "avatar-09.png", banner: "avatar-09-bg.jpg" },
  { id: "avatar-10", portrait: "avatar-10.png", banner: "avatar-10-bg.jpg" },
  { id: "avatar-11", portrait: "avatar-11.png", banner: "avatar-11-bg.jpg" },
];
