// GENERATED by scripts/gen-agent-art.mjs. Do not edit by hand.
//
// The gradient thumbnails in `public/agent-art/`, sorted, as a typed list. §5.1 requires the list to
// be built at BUILD TIME rather than read from a directory at runtime — a browser cannot list a
// directory, and a server that could would be answering a question whose answer must be identical on
// every replica.
//
// SORTED EXPLICITLY, because the sort order IS the mapping: `artFor` hashes an agent's uuid to an
// index into this array, so a list in a different order is a different gradient for every agent in
// the workspace. Directory iteration order is not stable across platforms and this project has
// already been bitten once by a platform-dependent path.
//
// `test:agent-art` asserts this matches what is actually in `public/agent-art`.

export const AGENT_ART_FILES: readonly string[] = [
  "aura-01.jpg",
  "aura-02.jpg",
  "aura-03.jpg",
  "aura-04.jpg",
  "aura-05.jpg",
  "aura-06.jpg",
  "aura-07.jpg",
  "aura-08.jpg",
  "aura-09.jpg",
  "aura-10.jpg",
  "aura-11.jpg",
  "aura-12.jpg",
  "aura-13.jpg",
  "aura-14.jpg",
  "aura-15.jpg",
  "aura-16.jpg",
  "aura-17.jpg",
  "aura-18.jpg",
  "aura-19.jpg",
  "aura-20.jpg",
  "aura-21.jpg",
];
