// GENERATED by scripts/gen-agent-faces.mjs. Do not edit by hand.
//
// The eleven portrait/badge/banner sets in `public/agent-faces/`, in source order, as a typed list.
// The list is built at BUILD TIME rather than read from a directory at runtime for the reason
// `agentArtFiles.ts` gives one asset set over: a browser cannot list a directory, and a server that
// could would be answering a question whose answer must be identical on every replica.
//
// THE ORDER IS THE MAPPING. An agent takes the entry at its own position in its workspace's
// creation order, so a list in a different order hands every agent in the workspace a different
// face. The ids are zero-padded precisely so that "source order" and "sorted order" are the same
// sequence on every platform — directory iteration order is not stable across them, and this
// project has already been bitten once by a platform-dependent path.
//
// `test:agent-faces` asserts this matches what is actually in `public/agent-faces`.

export interface AgentFaceFiles {
  /** The value `agents.picture` stores. */
  readonly id: string;
  /**
   * The free-standing portrait, for surfaces with room for a face — the agent card and the detail
   * header. No ring: the card mounts it on a tile that draws its own.
   */
  readonly portrait: string;
  /**
   * The circular badge with its own coloured ring, for dense rows — the sidebar, the Cockpit work
   * rows, the fleet strip, the command palette. Transparent around the ring.
   */
  readonly sidebar: string;
  /** The banner band, 2:1, in the hue this agent's background was painted in. */
  readonly banner: string;
}

export const AGENT_FACE_FILES: readonly AgentFaceFiles[] = [
  { id: "agent-01", portrait: "agent-01.png", sidebar: "agent-01-sidebar.png", banner: "agent-01-bg.jpg" },
  { id: "agent-02", portrait: "agent-02.png", sidebar: "agent-02-sidebar.png", banner: "agent-02-bg.jpg" },
  { id: "agent-03", portrait: "agent-03.png", sidebar: "agent-03-sidebar.png", banner: "agent-03-bg.jpg" },
  { id: "agent-04", portrait: "agent-04.png", sidebar: "agent-04-sidebar.png", banner: "agent-04-bg.jpg" },
  { id: "agent-05", portrait: "agent-05.png", sidebar: "agent-05-sidebar.png", banner: "agent-05-bg.jpg" },
  { id: "agent-06", portrait: "agent-06.png", sidebar: "agent-06-sidebar.png", banner: "agent-06-bg.jpg" },
  { id: "agent-07", portrait: "agent-07.png", sidebar: "agent-07-sidebar.png", banner: "agent-07-bg.jpg" },
  { id: "agent-08", portrait: "agent-08.png", sidebar: "agent-08-sidebar.png", banner: "agent-08-bg.jpg" },
  { id: "agent-09", portrait: "agent-09.png", sidebar: "agent-09-sidebar.png", banner: "agent-09-bg.jpg" },
  { id: "agent-10", portrait: "agent-10.png", sidebar: "agent-10-sidebar.png", banner: "agent-10-bg.jpg" },
  { id: "agent-11", portrait: "agent-11.png", sidebar: "agent-11-sidebar.png", banner: "agent-11-bg.jpg" },
];
