// GENERATED by scripts/gen-empty-faces.mjs. Do not edit by hand.
//
// The six badges in `public/empty-faces/`, in source order, as a typed list. Built at BUILD TIME
// rather than read from a directory at runtime for `agentFaceFiles.ts`'s reason: a browser cannot
// list a directory, and a server that could would be answering a question whose answer must be
// identical on every replica.
//
// THE ORDER IS THE DESIGN. The product owner asked for img1 through img6 in that order and named
// shuffling as the thing not to do, so the row draws this list front to back and nothing sorts,
// rotates or randomises it. The ids are zero-padded precisely so that "source order" and "sorted
// order" are the same sequence on every platform — directory iteration order is not stable across
// them, and this project has already been bitten once by a platform-dependent path.
//
// `test:empty-faces` asserts this matches what is actually in `public/empty-faces`.

export interface EmptyFaceFile {
  /** Stable id, and the basename without its extension. */
  readonly id: string;
  /** The badge: a circular illustration, transparent outside its own rim. */
  readonly file: string;
}

export const EMPTY_FACE_FILES: readonly EmptyFaceFile[] = [
  { id: "empty-01", file: "empty-01.png" },
  { id: "empty-02", file: "empty-02.png" },
  { id: "empty-03", file: "empty-03.png" },
  { id: "empty-04", file: "empty-04.png" },
  { id: "empty-05", file: "empty-05.png" },
  { id: "empty-06", file: "empty-06.png" },
];
