// Writes `src/lib/icons/generated/` out of `@hugeicons/core-free-icons`. Run `npm run gen:icons`.
//
// WHY A GENERATOR AND NOT AN IMPORT. `@hugeicons/react` renders a mark by walking an array of path
// tuples at runtime, which makes the icon set a RUNTIME DEPENDENCY of the composer's control bar —
// the one row in this product that has to be on screen before anything else is. This script moves
// that work to authoring time: the package is read here, the marks are written out as ordinary
// committed components, and nothing under `src/` imports from `@hugeicons/*` at all. The package is
// a devDependency for exactly that reason, and `test:icon-deps` fails if it stops being one.
//
// ── THE STROKE DECISION (icons_integration §3.2 / D1) ───────────────────────────────────────────
//
// EVERY MARK IS DRAWN AT `ICON.strokeWidth`, WHICH IS 1.75, AND NOTHING COMPENSATES BY SIZE.
//
// §3.2 asks for a decision and gives the test for it: go and read what the existing factory does at
// 14px and match it exactly. `components/panelIcons.tsx` puts a constant `ICON.strokeWidth` on the
// `<svg>` element and lets the 24-unit viewBox scale it down with the glyph — so at 14px it draws
// 1.02 device pixels and accepts the optical thinning rather than correcting for it. This generator
// draws through that same factory and therefore inherits that behaviour exactly. The alternative
// §3.2 offers, `strokeWidth = ICON.strokeWidth * 24 / size`, is deliberately NOT used: it would be
// a third behaviour in a codebase that already has one, and every Lucide-geometry mark in the app
// would then sit lighter than the HugeIcons mark beside it at every size except 24.
//
// The package's own payload is 1.5 — and 2 on `GameController03Icon`, which is the sidebar rail's
// Cockpit mark and would have sat visibly heavier than its five neighbours. Both are stripped. A
// mark physically cannot carry its own weight after this script runs, which is the mechanical half
// of I1; `test:icon-stroke` is the other half.
//
// ── DETERMINISM (I3) ────────────────────────────────────────────────────────────────────────────
//
// Attributes are sorted alphabetically so output does not depend on the package's key order or on
// a Node version's object iteration. ELEMENT ORDER IS NOT SORTED, and that is not an oversight:
// order is paint order in SVG, so sorting the elements of a mark would reorder what covers what.
// The array the package ships is already a fixed sequence, so it is deterministic as it stands.
//
// CI runs this and fails if `git status --porcelain` is non-empty, so hand-editing a generated file
// is a build failure rather than a surprise three weeks later.

import { readFile, writeFile, mkdir, readdir, rm } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const MANIFEST = path.join(HERE, "..", "src", "lib", "icons", "manifest.ts");
const OUT = path.join(HERE, "..", "src", "lib", "icons", "generated");

/** The manifest is data — `key: "SomeIcon"` — so its values are readable without a TS loader. */
async function exportNames() {
  const source = await readFile(MANIFEST, "utf8");
  const found = [...source.matchAll(/:\s*"([A-Za-z0-9]+Icon)"/g)].map((m) => m[1]);
  if (found.length === 0) throw new Error(`no icon names found in ${MANIFEST}`);
  return [...new Set(found)].sort();
}

/**
 * One element of a mark, as JSX.
 *
 * `stroke` and `strokeWidth` are dropped because they move to the `<svg>`; `key` is dropped because
 * these are literal siblings in a fragment rather than a mapped array. The four fill-only elements
 * in the set — a solid dot on `ClipboardListIcon`, two on `CloudSyncIcon`, one on
 * `SquareArrowOutUpRightIcon` — get an explicit `stroke="none"`, because without it they would
 * INHERIT the factory's `currentColor` stroke and render as a filled shape wearing a 1.75 outline.
 */
function element([tag, attrs]) {
  const out = {};
  for (const [k, v] of Object.entries(attrs)) {
    if (k === "key" || k === "stroke" || k === "strokeWidth") continue;
    out[k] = v;
  }
  if (!("stroke" in attrs)) out.stroke = "none";
  const rendered = Object.keys(out)
    .sort()
    .map((k) => `${k}="${out[k]}"`)
    .join(" ");
  return `      <${tag} ${rendered} />`;
}

function component(name, payload) {
  return `// GENERATED BY scripts/gen-icons.mjs — DO NOT EDIT.
//
// Source: \`${name}\` from @hugeicons/core-free-icons. Stroke comes from \`ICON.strokeWidth\` at the
// <svg>, via the one factory in components/panelIcons.tsx. Re-run \`npm run gen:icons\` to change it.

import { svg, type IconProps } from "../../../components/panelIcons.tsx";

export function ${name}(p: IconProps) {
  return svg(
    p,
    <>
${payload.map(element).join("\n")}
    </>,
  );
}
`;
}

const names = await exportNames();
const icons = await import("@hugeicons/core-free-icons");

// FAIL LOUDLY, NEVER SILENTLY. A future package version that renames a mark must break the build
// here, with the name printed, rather than quietly shipping a blank square into a filter bar.
const missing = names.filter((n) => !Array.isArray(icons[n]));
if (missing.length > 0) {
  console.error(
    `gen-icons: ${missing.length} name(s) in manifest.ts are not exported by ` +
      `@hugeicons/core-free-icons:\n  ${missing.join("\n  ")}`,
  );
  process.exit(1);
}

await mkdir(OUT, { recursive: true });

// Remove marks a manifest edit has dropped, so the directory is the manifest rather than the union
// of every manifest there has ever been. `test:icon-registry` would catch a leftover as a dead
// entry; deleting it here means it never reaches the branch.
const keep = new Set([...names.map((n) => `${n}.tsx`), "index.ts"]);
for (const file of await readdir(OUT)) {
  if (!keep.has(file)) await rm(path.join(OUT, file));
}

for (const name of names) {
  await writeFile(path.join(OUT, `${name}.tsx`), component(name, icons[name]), "utf8");
}

const barrel = `// GENERATED BY scripts/gen-icons.mjs — DO NOT EDIT.
//
// The barrel over the ${names.length} committed marks. \`registry.ts\` is the only file that imports it: a
// component asks for \`Icon.agents.fork\`, never for \`GitForkIcon\`, and \`test:icon-registry\` fails on
// any call site that reaches past the registry into this directory.

${names.map((n) => `export { ${n} } from "./${n}.tsx";`).join("\n")}
`;
await writeFile(path.join(OUT, "index.ts"), barrel, "utf8");

console.log(`gen-icons: wrote ${names.length} marks to src/lib/icons/generated/`);
