-- 003_identity — the same tables, in what SQLite has.
--
-- Read the Postgres version of this migration for why any of these columns exist. This file
-- is the translation, and the translation is where the two databases stop agreeing:
--
--   uuid            -> TEXT. Ids are generated by the application on both drivers anyway
--                      (randomUUID), so the Postgres DEFAULT is a convenience for hand-written
--                      SQL and never the source of an id the code has seen.
--   citext          -> TEXT COLLATE NOCASE. Same effect for the thing that matters: the
--                      UNIQUE index is case-insensitive, so Ada@example.com and
--                      ada@example.com cannot both be inserted.
--   timestamptz     -> TEXT holding ISO-8601 UTC. The Postgres driver hands its timestamps
--                      back as ISO-8601 strings too, so both drivers produce the same shape;
--                      what SQLite loses is the ability to do date arithmetic in SQL, which
--                      nothing here does.
--   bigserial       -> INTEGER PRIMARY KEY AUTOINCREMENT, SQLite's own monotonic counter.
--   inet            -> TEXT. No validation, and none is wanted: an audit row must record
--                      what arrived, including something that is not an address.
--   json            -> TEXT, as everywhere else on this driver.
--
-- The ON DELETE CASCADE clauses are written out even though this database does not enforce
-- foreign keys (PRAGMA foreign_keys is off here, as it has always been). They document the
-- intent and they are what a future `PRAGMA foreign_keys = ON` would enforce; leaving them
-- out would make the two files describe different relationships.

CREATE TABLE users (
  id           TEXT PRIMARY KEY,
  external_id  TEXT NOT NULL COLLATE NOCASE,
  email        TEXT NOT NULL COLLATE NOCASE,
  display_name TEXT,
  created_at   TEXT NOT NULL,
  deleted_at   TEXT
);

CREATE UNIQUE INDEX users_external_id ON users (external_id);
CREATE UNIQUE INDEX users_email       ON users (email);

CREATE TABLE workspaces (
  id         TEXT PRIMARY KEY,
  slug       TEXT NOT NULL COLLATE NOCASE,
  name       TEXT NOT NULL,
  kind       TEXT NOT NULL CHECK (kind IN ('personal', 'team')),
  plan       TEXT NOT NULL DEFAULT 'free',
  created_at TEXT NOT NULL,
  deleted_at TEXT
);

CREATE UNIQUE INDEX workspaces_slug ON workspaces (slug);

CREATE TABLE workspace_members (
  workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  user_id      TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  role         TEXT NOT NULL CHECK (role IN ('owner', 'admin', 'member')),
  created_at   TEXT NOT NULL,
  PRIMARY KEY (workspace_id, user_id)
);

CREATE INDEX workspace_members_user ON workspace_members (user_id);

CREATE TABLE audit_log (
  id            INTEGER PRIMARY KEY AUTOINCREMENT,
  workspace_id  TEXT,
  actor_user_id TEXT,
  action        TEXT NOT NULL,
  target_type   TEXT,
  target_id     TEXT,
  metadata      TEXT NOT NULL DEFAULT '{}',
  ip            TEXT,
  created_at    TEXT NOT NULL
);

CREATE INDEX audit_log_workspace ON audit_log (workspace_id, created_at DESC);
CREATE INDEX audit_log_action    ON audit_log (action, created_at DESC);
