-- 008_agents — the agent list stops being a directory listing.
--
-- Read the Postgres version for what this is for and for the slug uniqueness change. Same
-- translation as 003: uuid -> TEXT (ids are generated by the application on both drivers),
-- timestamptz -> TEXT ISO-8601, json -> TEXT, boolean -> INTEGER 0/1.

CREATE TABLE agents (
  id               TEXT PRIMARY KEY,
  workspace_id     TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
  slug             TEXT NOT NULL,
  display_name     TEXT,
  description      TEXT,
  connectors       TEXT NOT NULL DEFAULT '[]',
  mcp_tools        TEXT NOT NULL DEFAULT '[]',
  required_env     TEXT NOT NULL DEFAULT '[]',
  default_provider TEXT NOT NULL DEFAULT 'fake',
  hand_written     INTEGER NOT NULL DEFAULT 0,
  current_version  INTEGER NOT NULL DEFAULT 1,
  creation_cost    REAL,
  created_by       TEXT REFERENCES users(id),
  created_at       TEXT NOT NULL,
  deleted_at       TEXT,
  UNIQUE (workspace_id, slug)
);

CREATE INDEX agents_ws_created ON agents (workspace_id, created_at DESC);

CREATE TABLE agent_versions (
  id         TEXT PRIMARY KEY,
  agent_id   TEXT NOT NULL REFERENCES agents(id) ON DELETE CASCADE,
  version    INTEGER NOT NULL,
  manifest   TEXT NOT NULL,
  created_by TEXT REFERENCES users(id),
  created_at TEXT NOT NULL,
  UNIQUE (agent_id, version)
);
