// The three caps that stand between an infinite-loop agent and a five-figure surprise.
//
// WHY THESE ARE SEPARATE FROM EVERY OTHER LIMIT IN THIS CODEBASE. The budget gate bounds what a
// workspace STARTS against a ceiling it chose; the platform-key ceiling bounds what WE pay for a
// workspace on its plan; the tier's run quota bounds how many things it may do in a month. All
// three are agreements. These are not agreements — they are the answers to "what if the agreement
// was made by a bot", and they exist because every figure above is one somebody could deliberately
// max out.
//
// THE FIRST-WEEK CAP IS ABOUT ACCOUNTS, NOT USAGE. Fifty dollars of inference in seven days is a
// perfectly reasonable amount for a real customer and a wildly abnormal amount for one who signed
// up on Tuesday. The distinction the cap draws is not "too much" but "too much, too early", which
// is the shape of a stolen card and of a farm, and neither is fixed by a bigger number.
//
// THE 2× CAP IS ABOUT LOOPS. An agent that calls itself is not malice, it is a Tuesday — and the
// specification's own example is the right one: a fan-out that ran overnight. Doubling the included
// credit is the point past which "this is unusual" stops being a guess, and re-checking the card is
// the cheapest thing that distinguishes a real customer having a bad deploy from a card that will
// charge back.
//
// AND THE ANOMALY FREEZE BIASES TOWARD FALSE POSITIVES, deliberately and against instinct. A false
// positive is somebody annoyed for the time it takes to answer a support message. A false negative
// is a bill nobody can collect and an incident with a number attached. The specification says to
// bias this way; this file agrees loudly so nobody quietly retunes it later.
//
// EVERY THRESHOLD IS A CONSTANT IN THIS FILE, exported, and read by the suite. Not an env var —
// a limit that protects the platform's money should move by a reviewed change rather than by
// somebody with shell access at three in the morning, which is exactly the moment somebody would
// be tempted.

/** New accounts are judged on a shorter clock than established ones. */
export const NEW_ACCOUNT_DAYS = 7;

/** The most a workspace may spend on OUR key in its first week, whatever its plan includes. */
export const NEW_ACCOUNT_CAP_USD = 50;

/**
 * The multiple of included credit past which metered billing stops and the card is re-checked.
 *
 * TWO, and the number matters less than the fact that there is one. What it prevents is the
 * unbounded case: an agent looping overnight, a retry storm against a provider that is timing out,
 * a dataset somebody generated by accident with ten thousand rows in it.
 */
export const RUNAWAY_MULTIPLE = 2;

/** Per user, sliding. A floor rather than a target — a legitimate agent is nowhere near it. */
export const USER_RATE_LIMIT_PER_MINUTE = 100;

/** An hour that costs more than this multiple of the trailing day's average hour is an anomaly. */
export const ANOMALY_MULTIPLE = 10;

/**
 * The smallest trailing average worth comparing against.
 *
 * WITHOUT THIS THE RULE FIRES ON EVERY NEW WORKSPACE. A workspace whose trailing 24 hours cost two
 * cents has an average hour of a tenth of a cent, and its first real hour of work is a thousand
 * times that — which is not an anomaly, it is somebody starting. A ratio needs a denominator big
 * enough to mean something, and this is that floor.
 */
export const ANOMALY_MIN_BASELINE_USD = 1;

export type CapKind = "new_account" | "runaway" | "anomaly";

export interface CapBreach {
  kind: CapKind;
  /** What was spent, and what it was measured against. Both, because a refusal has to say why. */
  spentUsd: number;
  capUsd: number;
  message: string;
}

export interface SpendFacts {
  /** How long this workspace has existed, in days. Null when unknown — see `newAccountBreach`. */
  ageDays: number | null;
  /** What the PLATFORM has paid for this workspace in its first week. */
  firstWeekPlatformUsd: number;
  /** What the platform has paid this period, against what the plan includes. */
  periodPlatformUsd: number;
  includedCreditUsd: number;
  /** The last hour, and the average hour of the day before it. */
  lastHourUsd: number;
  trailingDayAverageHourUsd: number;
}

/**
 * Fifty dollars in the first week, whatever the plan says.
 *
 * AN UNKNOWN AGE IS TREATED AS ESTABLISHED, which is the one place this file gives the benefit of
 * the doubt. A workspace whose creation time cannot be read is far more likely to be a data problem
 * than a farm, and freezing every workspace on a failed lookup is a worse outage than missing one
 * account for the time it takes to fix the lookup.
 */
export function newAccountBreach(facts: SpendFacts): CapBreach | null {
  if (facts.ageDays === null || facts.ageDays > NEW_ACCOUNT_DAYS) return null;
  if (facts.firstWeekPlatformUsd < NEW_ACCOUNT_CAP_USD) return null;
  return {
    kind: "new_account",
    spentUsd: facts.firstWeekPlatformUsd,
    capUsd: NEW_ACCOUNT_CAP_USD,
    // NAMES SUPPORT RATHER THAN A LIMIT, because for the population this catches, waiting does not
    // help and neither does upgrading. Somebody has to look.
    message:
      `this workspace has used $${NEW_ACCOUNT_CAP_USD} of inference in its first week, which is ` +
      "unusual enough that we have paused it — email contact@jaroku.dev and we will sort it out",
  };
}

/**
 * Twice the included credit, before metered billing takes over.
 *
 * A PLAN WITH NO INCLUDED CREDIT HAS NO RUNAWAY CAP HERE, and that is correct rather than a gap:
 * Free includes nothing and is bounded by `platformKeyCeilingUsd` instead, which is a much smaller
 * number. This cap is about the paid tiers, where the ceiling is deliberately generous.
 */
export function runawayBreach(facts: SpendFacts): CapBreach | null {
  if (facts.includedCreditUsd <= 0) return null;
  const cap = facts.includedCreditUsd * RUNAWAY_MULTIPLE;
  if (facts.periodPlatformUsd < cap) return null;
  return {
    kind: "runaway",
    spentUsd: facts.periodPlatformUsd,
    capUsd: cap,
    message:
      `this workspace has used $${facts.periodPlatformUsd.toFixed(2)} of inference this period, ` +
      `which is more than twice the $${facts.includedCreditUsd} included — confirm the payment ` +
      "method on the Billing tab to keep going, or check whether an agent is looping",
  };
}

/**
 * An hour that costs ten times the trailing day's average hour.
 *
 * THE FLOOR IS WHAT MAKES THIS USABLE. Without `ANOMALY_MIN_BASELINE_USD` the rule fires on every
 * workspace's first real hour of work, because the denominator is a rounding error — and a rule
 * that cries wolf on day one is a rule somebody switches off in week two.
 */
export function anomalyBreach(facts: SpendFacts): CapBreach | null {
  if (facts.trailingDayAverageHourUsd < ANOMALY_MIN_BASELINE_USD) return null;
  const cap = facts.trailingDayAverageHourUsd * ANOMALY_MULTIPLE;
  if (facts.lastHourUsd < cap) return null;
  return {
    kind: "anomaly",
    spentUsd: facts.lastHourUsd,
    capUsd: cap,
    message:
      `this workspace spent $${facts.lastHourUsd.toFixed(2)} in the last hour against an average ` +
      `of $${facts.trailingDayAverageHourUsd.toFixed(2)} — inference is paused pending a look. ` +
      "Email contact@jaroku.dev if this was deliberate.",
  };
}

/**
 * Every cap, in the order the answers are most useful.
 *
 * ORDERED RATHER THAN COLLECTED, and the order is which sentence somebody should read first: a new
 * account has one thing to do (write in), a runaway has another (check the card, look for a loop),
 * and an anomaly is the vaguest of the three. Reporting all of them would be three paragraphs
 * describing one situation.
 */
export function firstBreach(facts: SpendFacts): CapBreach | null {
  return newAccountBreach(facts) ?? runawayBreach(facts) ?? anomalyBreach(facts);
}
