// I3: the committed marks are what the generator would write, byte for byte.
//
// THE DRIFT GUARD, and the reason generated output is checked in at all. Committing machine-written
// files buys an offline build and a readable diff; what it costs is the chance that somebody edits
// one by hand and the next `npm run gen:icons` silently reverts them three weeks later. This makes
// that a build failure at the moment it happens instead.
//
// IT RUNS THE GENERATOR FOR REAL. An in-memory reimplementation of the emitter would be a second
// copy of the thing under test — it would agree with itself and say nothing about the file that
// actually runs. So: read what is committed, run the generator over the working tree, read again,
// compare. A failure therefore leaves the tree REGENERATED, which is the state somebody wants to be
// in anyway; the message says to commit it.
//
// CI ASSERTS THE SAME PROPERTY A SECOND WAY, with `git status --porcelain` after the generator
// step. That is not redundant: this suite catches a hand-edited mark, and the CI step catches a
// manifest edit that was committed without re-running the generator at all.
//
//   npm run test:icon-generated

import { readdirSync } from "node:fs";
import { spawnSync } from "node:child_process";

import { check, done, read } from "./harness.ts";

const DIR = "src/lib/icons/generated";

const before = new Map<string, string>(
  readdirSync(DIR).sort().map((f) => [f, read(`${DIR}/${f}`)]),
);

const run = spawnSync("node", ["scripts/gen-icons.mjs"], { encoding: "utf8" });

console.log("\nthe generator runs clean");
check("exit code 0", run.status === 0, run.stderr?.trim() || "");

const after = new Map<string, string>(
  readdirSync(DIR).sort().map((f) => [f, read(`${DIR}/${f}`)]),
);

console.log("\n...and produces exactly the committed set");
{
  const onlyCommitted = [...before.keys()].filter((f) => !after.has(f));
  const onlyWritten = [...after.keys()].filter((f) => !before.has(f));
  check("the same file list", onlyCommitted.length === 0 && onlyWritten.length === 0,
    `committed only: ${onlyCommitted.join(", ")} · written only: ${onlyWritten.join(", ")}`);
  check("118 files — 117 marks and the barrel", after.size === 118, `${after.size}`);
}

console.log("\n...byte for byte");
{
  const differing: string[] = [];
  for (const [file, text] of after) {
    if (before.get(file) !== text) differing.push(file);
  }
  for (const f of differing) console.log(`  FAIL ${f} differs — hand-edited, or the manifest moved without a re-run`);
  check("no committed mark differs from what the generator writes", differing.length === 0,
    differing.length ? "the tree is now regenerated — commit it" : "");
}

console.log("\nand it is deterministic — running it twice changes nothing");
{
  spawnSync("node", ["scripts/gen-icons.mjs"], { encoding: "utf8" });
  const third = readdirSync(DIR).sort().map((f) => read(`${DIR}/${f}`));
  check("a second run is byte-identical to the first",
    third.every((text, i) => text === [...after.values()][i]));
}

console.log("\nevery mark is a component, and the barrel names all of them");
{
  const marks = [...after.keys()].filter((f) => f !== "index.ts");
  const barrel = after.get("index.ts") ?? "";
  const missing = marks.filter((f) => !barrel.includes(`export { ${f.replace(".tsx", "")} }`));
  check("the barrel re-exports every mark", missing.length === 0, missing.join(", "));
  check("...and nothing else", (barrel.match(/^export \{/gm) ?? []).length === marks.length);
  check("every file says it is generated",
    marks.every((f) => after.get(f)!.startsWith("// GENERATED BY scripts/gen-icons.mjs — DO NOT EDIT.")));
}

done();
